Adding unit test for coverage
pravega/pravega-sensor-collector pull request #61
Opened 2024-02-20 17:35 UTC by kuldeepk3

2024-02-22 04:07 UTC, sachin-j-joshi requested changes
Please introduce a base class to avoid duplication of code.

2024-02-22 04:07 UTC, sachin-j-joshi commented on pravega-sensor-collector/src/test/java/io/pravega/sensor/collector/file/parquet/ParquetFileIngestServiceTest.java
> +            System.out.println("Create Stream do nothing");
Please remove System.out.println. 
Also looks like the code is still under construction here.

2024-02-22 04:07 UTC, sachin-j-joshi commented on pravega-sensor-collector/src/test/resources/RawFileIngestService.properties
> +PRAVEGA_SENSOR_COLLECTOR_RAW1_DELETE_COMPLETED_FILES_INTERVAL_IN_SECONDS=15
Please add newline.

2024-02-22 04:07 UTC, sachin-j-joshi commented on pravega-sensor-collector/src/test/java/io/pravega/sensor/collector/file/rawfile/RawFileIngestServiceTest.java
> +public class RawFileIngestServiceTest {
Looks like we can pull lots of common functionality into an abstract base class.
Both RawFileIngestServiceTest and ParquetFileIngestServiceTest can derive from it.

2024-02-22 04:07 UTC, sachin-j-joshi commented on pravega-sensor-collector/src/test/java/io/pravega/sensor/collector/file/parquet/ParquetFileIngestServiceTest.java
> +public class ParquetFileIngestServiceTest {
Please add some basic comment on what this class tests.

2024-02-22 05:21 UTC, kuldeepk3 commented on pravega-sensor-collector/src/test/resources/RawFileIngestService.properties
> +PRAVEGA_SENSOR_COLLECTOR_RAW1_DELETE_COMPLETED_FILES_INTERVAL_IN_SECONDS=15
done

2024-02-22 05:22 UTC, kuldeepk3 commented
updated pr and removed unwanted code

2024-02-27 03:50 UTC, sachin-j-joshi commented on pravega-sensor-collector/src/test/java/io/pravega/sensor/collector/file/MockFileIngestService.java
> +    @Override
where is this defined in base class?

2024-02-27 03:50 UTC, sachin-j-joshi commented on pravega-sensor-collector/src/test/java/io/pravega/sensor/collector/file/FileIngestServiceTest.java
> +        FileIngestService fileIngestService = new MockFileIngestService(deviceDriverConfig);
Does it make sense to move this to `@Before` ?

2024-02-27 04:20 UTC, sachin-j-joshi approved these changes
LGTM

2024-02-27 10:49 UTC, abhinb approved these changes

2024-02-27 10:50 UTC, merged